export const SCAVENGER_CLASSES: {[key: number]: string} = {
0: 'ipad',
1: 'foraminifera',
2: 'smoke detector',
3: 'football boot',
4: 'scallop',
5: 'coat rack',
6: 'coca cola bottle',
7: 'toy watering can',
8: 'ruler',
9: 'sun glasses',
10: 'computer mouse',
11: 'headset',
12: 'spoon',
13: 'teddy bear',
14: 'toy dinosaur',
15: 'norwegian flag',
16: 'toy sword',
17: 'sponge',
18: 'stapler',
19: 'toy motor saw',
20: '2nd ww bomb',
21: 'duct tape',
}
