export const SCAVENGER_CLASSES: {[key: number]: string} = {
0: 'watering can',
1: 'sponge',
2: 'chainsaw',
3: 'computer mouse',
4: 'foraminifera',
5: 'bottle',
6: 'flag',
7: 'stapler',
8: 'spoon',
9: 'tape',
10: 'teddybear',
11: 'ipad',
12: 'headset',
13: 'football boot',
14: 'coat rack',
15: 'sunglasses',
16: 'bomb',
17: 'sword',
18: 'smoke detector',
19: 'ruler',
20: 'dinosaur',
21: 'scallop',
}